name: kkkk
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jujutsu_kaisen.jpg
    - assets/OpenHeimer.jpg
    - assets/Gato de Botas.jpg
    - assets/Cidade de Deus.jpg
    - assets/Freira.jpg
    - assets/The_Purge.jpg
    - assets/The_Maze_Runner.jpg
    - assets/The_Jester.jpg
    - assets/corra.jpg
    - assets/bleachcat.jpg